### ISSUE TITLE
How to set user data on firebase  for initial user ?

### ISSUE THREAD

**Issue by amitmeh10** [an23lm/AncesTree#1]
Tell me how to set intial user . because app is crash on load user ...

**Comment by amitmeh10** [comment]
how did you set firebase database ..

**Comment by an23lm** [comment]
Hey, this build is not working currently. I've been quite busy. In fact, I've not built the login yet. Sorry about that.

**Comment by amitmeh10** [comment]
So it works ..  with firebase flow ..

**Comment by an23lm** [comment]
You can use any auth firebase provides, that's quite easy. After which you need to keep a track of all the users in a particular family tree. After which you can keep track of which "origins" aka which family tree he/she belongs to and load all the data accordingly. Check out the image below, it should give you an idea.
<img width="713" alt="screenshot 2018-09-20 at 6 06 33 pm" src="https://user-images.githubusercontent.com/5507600/45818714-2b5d8900-bd00-11e8-82bc-d43fce51f37a.png">
